version: '3'

services:
  sftp:
    networks:
      sftp-net:
    image: atmoz/sftp
    volumes:
        - ./sftpdata:/home/foo/upload
        - ./sftpconfig/users.conf:/etc/sftp/users.conf
    ports:
        - "2222:22"
    command: foo:pass:1001
    volumes:
     - ./sftpdata:/home
  sftp_portal:
    networks:
      sftp-net:
        aliases:
          - start-dash
    build: .
    volumes:
        - ./sftpconfig:/usr/src/app/sftpconfig
    ports:
      - "8085:8085"
    container_name: sftp-start-dash
    restart: always

networks:
  sftp-net: