version: '3'

services:
  sftp:
    networks:
      sftp-net:
    build: ./atmoz-sftp/.
    volumes:
        - ./sftpconfig/sftp:/etc/sftp
        - ./hostkeys/ssh_host_ed25519_key:/tmp/ssh_host_ed25519_key
        - ./hostkeys/ssh_host_rsa_key:/tmp/ssh_host_rsa_key 
        - ./run-from-compose.sh:/run-from-compose.sh
    ports:
        - "2222:22"
    command: sh /run-from-compose.sh 
  sftp_portal:
    networks:
      sftp-net:
        aliases:
          - start-dash
    build: .
    volumes:
        - ./sftpconfig/sftp:/usr/src/app/sftpconfig
    ports:
      - "8085:8085"
    container_name: sftp-start-dash
    restart: always

networks:
  sftp-net: